; G-Code generated by Simplify3D(R) Version 3.0.2
; Jun 6, 2016 at 11:17:51 AM
; Settings Summary
;   processName,Process1
;   applyToModels,test(2)
;   profileName,MakerGear M2 (24V V3b hotend)(2) (modified)
;   profileVersion,2016-02-11 11:33:28
;   baseProfile,
;   printMaterial,PLA
;   printQuality,Medium
;   printExtruders,
;   extruderName,Primary Extruder
;   extruderToolheadNumber,0
;   extruderDiameter,0.35
;   extruderAutoWidth,1
;   extruderWidth,0.42
;   extrusionMultiplier,0.9
;   extruderUseRetract,1
;   extruderRetractionDistance,1
;   extruderExtraRestartDistance,0
;   extruderRetractionZLift,0
;   extruderRetractionSpeed,2400
;   extruderUseCoasting,0
;   extruderCoastingDistance,0.2
;   extruderUseWipe,0
;   extruderWipeDistance,5
;   primaryExtruder,0
;   layerHeight,0.2
;   topSolidLayers,3
;   bottomSolidLayers,3
;   perimeterOutlines,3
;   printPerimetersInsideOut,1
;   startPointOption,2
;   startPointOriginX,0
;   startPointOriginY,0
;   startPointOriginZ,300
;   sequentialIslands,0
;   spiralVaseMode,0
;   firstLayerHeightPercentage,90
;   firstLayerWidthPercentage,100
;   firstLayerUnderspeed,0.5
;   useRaft,0
;   raftExtruder,0
;   raftLayers,3
;   raftOffset,3
;   raftSeparationDistance,0.14
;   raftInfill,85
;   disableRaftBaseLayers,0
;   useSkirt,0
;   skirtExtruder,0
;   skirtLayers,1
;   skirtOutlines,2
;   skirtOffset,4
;   usePrimePillar,0
;   primePillarExtruder,999
;   primePillarWidth,12
;   primePillarLocation,7
;   primePillarSpeedMultiplier,1
;   useOozeShield,0
;   oozeShieldExtruder,999
;   oozeShieldOffset,2
;   oozeShieldOutlines,1
;   oozeShieldSidewallShape,1
;   oozeShieldSidewallAngle,30
;   oozeShieldSpeedMultiplier,1
;   infillExtruder,0
;   internalInfillPattern,Fast Honeycomb
;   externalInfillPattern,Rectilinear
;   infillPercentage,30
;   outlineOverlapPercentage,15
;   infillExtrusionWidthPercentage,100
;   minInfillLength,5
;   infillLayerInterval,1
;   infillAngles,0
;   overlapInfillAngles,0
;   generateSupport,0
;   supportExtruder,0
;   supportInfillPercentage,30
;   supportExtraInflation,0
;   denseSupportLayers,0
;   denseSupportInfillPercentage,70
;   supportLayerInterval,1
;   supportHorizontalPartOffset,0.3
;   supportUpperSeparationLayers,1
;   supportLowerSeparationLayers,1
;   supportType,0
;   supportGridSpacing,4
;   maxOverhangAngle,45
;   supportAngles,0
;   temperatureName,Primary Extruder,Heated Bed
;   temperatureNumber,0,2
;   temperatureSetpointCount,1,1
;   temperatureSetpointLayers,1,1
;   temperatureSetpointTemperatures,215,85
;   temperatureStabilizeAtStartup,1,1
;   temperatureHeatedBed,0,1
;   temperatureRelayBetweenLayers,0,0
;   temperatureRelayBetweenLoops,0,0
;   fanLayers,1,2
;   fanSpeeds,0,100
;   blipFanToFullPower,1
;   adjustSpeedForCooling,1
;   minSpeedLayerTime,15
;   minCoolingSpeedSlowdown,20
;   increaseFanForCooling,0
;   minFanLayerTime,45
;   maxCoolingFanSpeed,100
;   increaseFanForBridging,0
;   bridgingFanSpeed,100
;   use5D,1
;   relativeEdistances,0
;   allowEaxisZeroing,1
;   independentExtruderAxes,0
;   includeM10123,0
;   stickySupport,1
;   applyToolheadOffsets,0
;   gcodeXoffset,0
;   gcodeYoffset,0
;   gcodeZoffset,0
;   overrideMachineDefinition,1
;   machineTypeOverride,0
;   strokeXoverride,200
;   strokeYoverride,250
;   strokeZoverride,200
;   originOffsetXoverride,0
;   originOffsetYoverride,0
;   originOffsetZoverride,0
;   homeXdirOverride,-1
;   homeYdirOverride,-1
;   homeZdirOverride,-1
;   flipXoverride,1
;   flipYoverride,-1
;   flipZoverride,1
;   toolheadOffsets,0,0|0,0|0,0|0,0|0,0|0,0
;   overrideFirmwareConfiguration,1
;   firmwareTypeOverride,RepRap (Marlin/Repetier/Sprinter)
;   GPXconfigOverride,r2
;   baudRateOverride,115200
;   overridePrinterModels,1
;   printerModelsOverride,MakerGear_M2Single.stl
;   startingGcode,M108 S255 ; turn on M2 fans,G28 ; home all axes,G1 Y50 Z0.3 F9600 ; move forward to avoid binder clips,G1 X205 Z10 ; move off platform,G1 Z0.4 ; position nozzle,G92 E0 ; zero extruder,G1 E25 F225 ; purge nozzle,G92 E0 ; zero extruder,G1 X190 Z0.1 E1.0 F1200 ; slow wipe,G1 X180 Z0.25 ; lift
;   layerChangeGcode,
;   retractionGcode,
;   toolChangeGcode,
;   endingGcode,M104 S0 ; turn off extruder,M140 S0 ; turn off bed,G91 ; relative mode,G1 Z10 ; lift 10mm,G90 ; absolute mode,G28 X0 ; home X axis,M84 ; disable motors
;   createX3G,0
;   celebration,0
;   celebrationSong,Random Song
;   createMB5G,0
;   postProcessing,
;   defaultSpeed,4800
;   outlineUnderspeed,0.6
;   solidInfillUnderspeed,0.8
;   supportUnderspeed,0.8
;   rapidXYspeed,18000
;   rapidZspeed,1200
;   minBridgingArea,50
;   bridgingExtraInflation,0
;   bridgingExtrusionMultiplier,1
;   bridgingSpeedMultiplier,1
;   filamentDiameter,1.75
;   filamentPricePerKg,46
;   filamentDensity,1.25
;   useMinPrintHeight,0
;   minPrintHeight,0
;   useMaxPrintHeight,0
;   maxPrintHeight,0
;   useDiaphragm,0
;   diaphragmLayerInterval,20
;   robustSlicing,1
;   mergeAllIntoSolid,0
;   onlyRetractWhenCrossingOutline,1
;   retractBetweenLayers,1
;   useRetractionMinTravel,0
;   retractionMinTravel,3
;   retractWhileWiping,0
;   onlyWipeOutlines,1
;   avoidCrossingOutline,0
;   maxMovementDetourFactor,3
;   toolChangeRetractionDistance,12
;   toolChangeExtraRestartDistance,-0.5
;   toolChangeRetractionSpeed,600
;   allowThinWallGapFill,1
;   thinWallAllowedOverlapPercentage,10
;   horizontalSizeCompensation,0
G90
M82
M106 S0
M140 S85
M190 S85
M104 S215 T0
M109 S215 T0
M108 S255 ; turn on M2 fans
G28 ; home all axes
G1 Y50 Z0.3 F9600 ; move forward to avoid binder clips
G1 X205 Z10 ; move off platform
G1 Z0.4 ; position nozzle
G92 E0 ; zero extruder
G1 E25 F225 ; purge nozzle
G92 E0 ; zero extruder
G1 X190 Z0.1 E1.0 F1200 ; slow wipe
G1 X180 Z0.25 ; lift
G92 E0
G1 E-1.0000 F2400
G1 Z0.180 F1200
; layer 1, Z = 0.18
T0
; tool H0.200 W0.420
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 E0.0000 F720
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 2, Z = 0.38
M106 S255
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z0.380 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 3, Z = 0.58
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z0.580 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 4, Z = 0.78
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z0.780 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 5, Z = 0.98
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z0.980 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 6, Z = 1.18
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z1.180 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 7, Z = 1.38
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z1.380 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 8, Z = 1.58
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z1.580 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 9, Z = 1.78
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z1.780 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 10, Z = 1.98
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z1.980 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 11, Z = 2.18
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z2.180 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 12, Z = 2.38
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z2.380 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 13, Z = 2.58
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z2.580 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 14, Z = 2.78
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z2.780 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 15, Z = 2.98
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z2.980 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 16, Z = 3.18
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z3.180 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 17, Z = 3.38
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z3.380 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 18, Z = 3.58
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z3.580 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 19, Z = 3.78
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z3.780 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 20, Z = 3.98
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z3.980 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 21, Z = 4.18
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z4.180 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 22, Z = 4.38
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z4.380 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 23, Z = 4.58
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z4.580 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 24, Z = 4.78
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z4.780 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer 25, Z = 4.98
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.210 Y120.210 F18000
G1 Z4.980 F1200
G1 E0.0000 F2400
G92 E0
G1 X104.790 Y120.210 E0.3011 F576
G1 X104.790 Y129.790 E0.6022
G1 X95.210 Y129.790 E0.9033
G1 X95.210 Y120.210 E1.2044
; inner perimeter
; inner perimeter
; outer perimeter
G1 X95.790 Y120.790 F18000
G92 E0
G1 X95.790 Y129.210 E0.2646 F576
G1 X104.210 Y129.210 E0.5293
G1 X104.210 Y120.790 E0.7939
G1 X95.790 Y120.790 E1.0586
G92 E0
G1 E-1.0000 F2400
; layer end
M104 S0 ; turn off extruder
M140 S0 ; turn off bed
G91 ; relative mode
G1 Z10 ; lift 10mm
G90 ; absolute mode
G28 X0 ; home X axis
M84 ; disable motors
; Build Summary
;   Build time: 0 hours 3 minutes
;   Filament length: 56.6 mm (0.06 m)
;   Plastic volume: 136.08 mm^3 (0.14 cc)
;   Plastic weight: 0.17 g (0.00 lb)
;   Material cost: 0.01
